# Generated by Django 3.2.23 on 2024-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Project description', null=True, verbose_name='description'),
        ),
    ]
