# Generated by Django 3.2.23 on 2024-01-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='owner',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(help_text='User ID', on_delete=django.db.models.deletion.CASCADE, related_name='gm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
