# Generated by Django 3.2.23 on 2024-01-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
